# G3 campaign point (#25; Scott approved the campaign 2026-10-08): the multi-node engine on RODA
# v205, N nodes, one cohort-mode invocation over the first COHORT samples of the recorded cohort
# (results/cohort/PRJNA398089/runs.tsv), the shard loaded once. Generated by scripts/g3/mkspec.sh
# from scripts/g3/campaign.body.sh; the parameters are the block below.
# Batches of the one invocation c<COHORT> (defaults: SDK emitter, sample-parallel, T16, LPT):
#   0  parallel:lpt, every sample, INFLIGHT per node (weight = pairs, runs.tsv read_count)
#   1  parallel:mod, the same samples (the placement control, j mod N; CONTROL_MOD=1, N > 1)
#   2  parallel:lpt again (the within-run spread; REPEAT_LPT=1)
#   3… sample 1 block-striped across the N nodes, C1_REPS times (N > 1), then sample 1 on its
#      home node alone, C1_REPS times (the single-sample points on the same load)
# Each node fetches only the inputs it reads (its home samples in batches 0-2 and sample 1), each
# checked against its sha256 metadata; inputs are page-cache warm when classified (staged just
# before, as upstream's are in U1/U2). Every output is an s3:// object under
# <cohort prefix>/out/c<COHORT>/<batch>-<sample>/{output,report}. No upstream arm here: Law 1 for
# these paths rests on make oracle-cohort (LPT included) and on the cross-check of the cohort's
# outputs with U1's (equal ETags, the same 8 MiB part layout). The cohort post
# (scripts/post/<spec>.cohort.sh) derives every table offline from the pushed stderr and
# outputs.tsv. Streaming: every engine ak2 line goes into the run log as written.
@PARAMS@
W=$HOME/ak2; mkdir -p "$W"
SHA=$(echo "$AK2_COHORT_ID" | cut -d- -f3)
RANK=$AK2_ENGINE_RANK; N=$AK2_ENGINE_N
set -- $AK2_DATASETS
U=${1#s3://}; RB=${U%%/*}; HK=${U#*/}; RP=${HK%/*}
U=${4#s3://}; B=${U%%/*}; CK=${U#*/}; CK=${CK%/}
fail() { ak2_say "ERROR: $*"; exit 1; }
hex64() { [[ $1 =~ ^[0-9a-f]{64}$ ]]; }
# AK2_REHEARSE_* are make rehearse's seams (scripts/lib/cohort_rehearse.sh): run.sh refuses them in
# a spec's env and never sets them, so on AWS they are always unset.
[ -n "$AK2_COHORT_ID" ] && [ -n "$RANK" ] && [ "$N" = "${AK2_REHEARSE_N:-$WANT_N}" ] ||
  fail "not a member of a ${AK2_REHEARSE_N:-$WANT_N}-node cohort (make run ... NODES=$WANT_N)"
ak2_say "$EXP cohort $AK2_COHORT_ID rank $RANK of $N, commit $SHA; RODA $RB/$RP; samples $B/$CK; cohort $COHORT"

ak2_phase setup
sudo -n dnf install -y -q git gcc make jq gzip tar findutils python3 > "$W/dnf.log" 2>&1 || { tail -20 "$W/dnf.log"; fail "dnf install failed"; }
git clone -q https://github.com/scttfrdmn/aws-kraken2.git "$W/repo" || fail "clone failed"
git -C "$W/repo" checkout -q "$SHA" || fail "checkout $SHA failed"
GOV=$(awk '$1=="go"{print $2}' "$W/repo/go.mod")
curl -fsSL --retry 5 --retry-delay 5 "https://go.dev/dl/go$GOV.linux-arm64.tar.gz" -o "$W/go.tgz" || fail "Go download failed"
tar -xzf "$W/go.tgz" -C "$W" || fail "Go unpack failed"
export PATH="$W/go/bin:$PATH"
(cd "$W/repo" && make build) > "$W/make-build.out" 2>&1 || { tail -30 "$W/make-build.out"; fail "make build failed"; }
OURS="$W/repo/bin/aws-kraken2"
TOKEN=$(curl -sf -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 300" http://169.254.169.254/latest/api/token)
IP=$(curl -sf -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)
[ -n "$IP" ] || fail "no private IP from IMDS"
NPROC=$(nproc)
[ "$INFLIGHT" = auto ] && INFLIGHT=$(( NPROC / 8 > 0 ? NPROC / 8 : 1 ))
ak2_say "built $(git -C "$W/repo" rev-parse HEAD); $(go version); ip $IP; nproc $NPROC; $(free -g | awk '/Mem:/{print "mem_gib " $2}'); threads $THREADS, inflight $INFLIGHT"

ak2_phase manifest
DB="$W/db/roda"; mkdir -p "$DB"
for f in opts.k2d taxo.k2d; do
  ak2_stage "s3://$RB/$RP/$f" "$DB/$f" || fail "stage of RODA $f failed"
  ak2_req GetObject 1 "$RB"
done
aws s3api head-object --no-sign-request --bucket "$RB" --key "$RP/hash.k2d" > "$W/head-hash.json" || fail "head-object hash.k2d failed"
ak2_req HeadObject 1 "$RB"
ETAG=$(jq -r '.ETag | gsub("\"";"")' "$W/head-hash.json"); SIZE=$(jq -r .ContentLength "$W/head-hash.json")
URL=${AK2_REHEARSE_HASH_URL:-"https://$RB.s3.$AK2_REGION.amazonaws.com/$RP/hash.k2d"}
ak2_say "RODA hash.k2d etag=$ETAG size=$SIZE"
# The first COHORT runs of the recorded cohort (rank order) and their pairs (the LPT weight).
RUNS="$W/repo/results/cohort/PRJNA398089/runs.tsv"
mapfile -t SAMPLES < <(awk -F'\t' -v c="$COHORT" 'NR>1 && $1<=c {print $2}' "$RUNS")
mapfile -t WEIGHTS < <(awk -F'\t' -v c="$COHORT" 'NR>1 && $1<=c {print $4}' "$RUNS")
# env.AK2_ACCESSIONS (a reference, @PRJNA398089:1-<COHORT>, or an older spec's literal list),
# resolved from this checkout at the run's commit: it must name exactly these samples.
if [ -n "${AK2_ACCESSIONS:-}" ]; then
  ACC=$("$W/repo/scripts/lib/accessions.sh" -r "$W/repo" "$AK2_ACCESSIONS") || fail "env.AK2_ACCESSIONS '$AK2_ACCESSIONS' does not resolve on the node"
  [ "$ACC" = "${SAMPLES[*]}" ] || fail "env.AK2_ACCESSIONS '$AK2_ACCESSIONS' does not name the first $COHORT runs of $RUNS"
  ak2_say "accessions: ${AK2_ACCESSIONS:0:40} -> $(wc -w <<< "$ACC") runs, as runs.tsv ranks 1-$COHORT"
fi
if [ -n "${AK2_REHEARSE_SAMPLES:-}" ]; then
  read -r -a SAMPLES <<< "$AK2_REHEARSE_SAMPLES"; read -r -a WEIGHTS <<< "$AK2_REHEARSE_WEIGHTS"
  COHORT=${#SAMPLES[@]}
fi
[ "${#SAMPLES[@]}" = "$COHORT" ] && [ "${#WEIGHTS[@]}" = "$COHORT" ] || fail "want $COHORT cohort runs and weights, got ${#SAMPLES[@]} and ${#WEIGHTS[@]}"
CD="$W/cohort"; mkdir -p "$CD"
OUT="$AK2_COHORT_PREFIX/out"
INV="c$COHORT"
M="$W/$INV.tsv"; : > "$M"
inputs() { echo "$CD/${1}_1.fastq.gz"; echo "$CD/${1}_2.fastq.gz"; }
line() {  # batch mode name weight sample
  local b=$1 mode=$2 s=$5 w=()
  [ "$4" != - ] && w=("weight=$4")
  local inf=$INFLIGHT; [ "$mode" = striped ] && inf=1
  printf '%s\t%s\t%s\tsdk\t%s' "$b" "$inf" "$mode" "$3"
  [ "${#w[@]}" -gt 0 ] && printf '\t%s' "${w[@]}"
  printf '\t--threads\t%s\t--output\t%s\t--report\t%s\t%s\t%s\n' "$THREADS" "$OUT/$INV/$3/output" "$OUT/$INV/$3/report" \
    "$CD/${s}_1.fastq.gz" "$CD/${s}_2.fastq.gz"
}
b=0
for ((j = 0; j < COHORT; j++)); do line "$b" parallel:lpt "$b-${SAMPLES[$j]}" "${WEIGHTS[$j]}" "${SAMPLES[$j]}" >> "$M"; done
b=$((b + 1))
if [ "$CONTROL_MOD" = 1 ] && [ "$N" -gt 1 ]; then
  for ((j = 0; j < COHORT; j++)); do line "$b" parallel:mod "$b-${SAMPLES[$j]}" "${WEIGHTS[$j]}" "${SAMPLES[$j]}" >> "$M"; done
  b=$((b + 1))
fi
if [ "$REPEAT_LPT" = 1 ]; then
  for ((j = 0; j < COHORT; j++)); do line "$b" parallel:lpt "$b-${SAMPLES[$j]}" "${WEIGHTS[$j]}" "${SAMPLES[$j]}" >> "$M"; done
  b=$((b + 1))
fi
S1=${SAMPLES[0]}
for ((k = 0; k < C1_REPS; k++)); do
  [ "$N" -gt 1 ] || break
  line "$b" striped "$b-$S1" - "$S1" >> "$M"; b=$((b + 1))
done
for ((k = 0; k < C1_REPS; k++)); do line "$b" parallel:lpt "$b-$S1" "${WEIGHTS[0]}" "$S1" >> "$M"; b=$((b + 1)); done
ak2_push "$M" "rank$RANK/$INV.tsv"
python3 "$W/repo/scripts/lib/cohort_place.py" table "$N" "$M" > "$W/placement.tsv" || fail "placement table failed"
ak2_push "$W/placement.tsv" "rank$RANK/placement.tsv"
mapfile -t NEED < <(python3 "$W/repo/scripts/lib/cohort_place.py" needs "$N" "$RANK" "$M")
ak2_say "manifest $INV: $(grep -c . "$M") lines in $b batches; rank $RANK reads ${#NEED[@]} samples"

ak2_phase fetch
# Each needed mate: GET, then sha256 against its metadata; 8 lanes.
FILES=()
for s in "${NEED[@]}"; do FILES+=("${s}_1.fastq.gz" "${s}_2.fastq.gz"); done
DEST=$CD; LANES=8
# scripts/g3/fetch.sh, a child process (its lanes are its own jobs, waited for by PID: the
# body's earlier wait -n, bare and then with -p over a PID list, miscounted at 8a6dbe6 and looped
# on "no such job" at 1a4dbfe), under a watchdog of FETCH_LIMIT seconds.
FETCH_LIMIT=1500
"$W/repo/scripts/g3/fetch.sh" "$B" "$CK" "$DEST" "$LANES" "${FILES[@]}" > "$W/fetched.txt" 2>&1 &
FP=$!
( sleep "$FETCH_LIMIT"; kill -TERM "$FP" 2>/dev/null ) > /dev/null 2>&1 &
WD=$!
wait "$FP"; FERR=$?
kill "$WD" 2>/dev/null
grep ERROR "$W/fetched.txt" | head -5
[ "$FERR" = 0 ] || { ak2_push "$W/fetched.txt" "rank$RANK/fetched.txt"; fail "input fetch failed"; }
NF=$(grep -vc ERROR "$W/fetched.txt")
[ "$NF" = $(( 2 * ${#NEED[@]} )) ] || fail "fetched $NF files, want $(( 2 * ${#NEED[@]} ))"
ak2_req GetObject "$(awk '!/ERROR/{n += int(($2 + 8388607) / 8388608)} END{print n+0}' "$W/fetched.txt")" "$B"
ak2_req HeadObject "$NF" "$B"
ak2_say "inputs staged and verified: $NF files, $(awk '!/ERROR/{s+=$2} END{printf "%.2f GB", s/1e9}' "$W/fetched.txt")"

ENGINE_ENV=(AK2_ENGINE_LISTEN="$IP" AK2_ENGINE_TIMEOUT=30m AK2_ENGINE_HASH_URL="$URL" AK2_ENGINE_HASH_ETAG="$ETAG"
  AK2_ENGINE_HASH_SIZE="$SIZE" AK2_TIMINGS=1 K2_DB_READ_THREADS=48)
COMMON=(--db "$DB" --paired)
env "${ENGINE_ENV[@]}" AK2_COHORT="$M" AK2_COHORT_CHECK=1 "$OURS" "${COMMON[@]}" > /dev/null 2> "$W/check.err" ||
  { cat "$W/check.err"; fail "cohort manifest $M does not check"; }
ak2_say "manifest $INV: $(grep "^cohort:" "$W/check.err" | tail -1)"

ak2_phase "inv-$INV"
# The engine's stderr to a file and, line by line as written, its ak2 lines into the run log.
# Order matters: the 2> process substitution forks with the stdout in effect at that point, so
# it comes before > /dev/null.
env "${ENGINE_ENV[@]}" AK2_ENGINE_RENDEZVOUS="$AK2_ENGINE_RENDEZVOUS/$INV" AK2_COHORT="$M" "$OURS" "${COMMON[@]}" \
  2> >(tee "$W/eng-$INV.stderr" | grep --line-buffered -E '^ak2-(sample|timing|engine)' | sed -u "s/^/[$INV] /") \
  > /dev/null
RC=$?
sleep 1 # let the tee drain
ak2_say "inv $INV rank $RANK exit $RC"
grep -vE '^ak2-(timing|engine|sample)' "$W/eng-$INV.stderr" | grep -v ' sequences ' | tail -5 | sed "s/^/[$INV stderr] /"
# Requests: the shard load's ranged GETs (RODA, anonymous); every S3 request of the process by
# operation (outputs and rendezvous, both clients); the rendezvous's own puts and gets.
F="$W/eng-$INV.stderr"
v=$(awk -F'\t' '$1=="ak2-engine" && $2=="load" {print $6}' "$F" | tail -1)
[ -n "$v" ] && ak2_req GetObject-range "$v" "$RB"
for op in put:PutObject get:GetObject create_multipart:CreateMultipartUpload upload_part:UploadPart \
          complete_multipart:CompleteMultipartUpload abort_multipart:AbortMultipartUpload; do
  v=$(awk -F'\t' -v k="${op%%:*}" '$1=="ak2-engine" && $2=="s3" { for (i = 3; i < NF; i++) if ($i == k) s += $(i+1) } END { print s+0 }' "$F")
  [ "$v" -gt 0 ] && ak2_req "${op#*:}" "$v" "$B"
done
v=$(awk -F'\t' '$1=="ak2-engine" && $2=="rendezvous" {print $4}' "$F" | tail -1); [ -n "$v" ] && ak2_req Rendezvous-PutObject "$v" "$B"
v=$(awk -F'\t' '$1=="ak2-engine" && $2=="rendezvous" {print $6}' "$F" | tail -1); [ -n "$v" ] && ak2_req Rendezvous-GetObject "$v" "$B"
ak2_push "$F" "rank$RANK/eng-$INV.stderr"
ak2_say "rank $RANK done (rc=$RC)"
exit "$RC"
