#!/usr/bin/env python3
"""E1's summary, generated: COHORT_DIR/tables/summary.md, from files in the record only.

  e1_summary.py COHORT_DIR

Reads COHORT_DIR/{cohort.json, rank-*.run.log, tables/{tidy,rates,batches,samples,consistency,
provenance}.tsv}, and, for the same-run input pairs, every other E1 cohort under results/g3/
(cohort.json spec runs/g3-e1.json) whose tables/tidy.tsv has both c1-striped-sdk and
c1-parallel-sdk. Every number printed names the file it comes from. Run by
scripts/post/g3-e1.cohort.sh after e1_consistency.py and e1_batches.py.
"""
import csv, glob, json, os, re, statistics, sys

d = os.path.normpath(sys.argv[1])
T = os.path.join(d, "tables")


def tsv(p):
    return list(csv.DictReader(open(p), delimiter="\t"))


coh = json.load(open(os.path.join(d, "cohort.json")))
batches = {r["batch"]: r for r in tsv(os.path.join(T, "batches.tsv"))}
samples = tsv(os.path.join(T, "samples.tsv"))
cons = tsv(os.path.join(T, "consistency.tsv"))
prov = {r["key"]: r["value"] for r in tsv(os.path.join(T, "provenance.tsv"))}
tidy = tsv(os.path.join(T, "tidy.tsv"))


def c1_pair(rows):
    """rank 0's c1-striped-sdk classify phase (N=8, striped) and c1-parallel-sdk's sample classify_s (one home node)."""
    st = pa = None
    for r in rows:
        if r["rank"] != "0":
            continue
        if r["invocation"] == "c1-striped-sdk" and r["kind"] == "phase" and r["metric"] == "classify":
            st = float(r["value"])
        if r["invocation"] == "c1-parallel-sdk" and r["kind"] == "sample" and r["metric"] == "classify_s":
            pa = float(r["value"])
    return st, pa


def f(x, n=2):
    return f"{x:.{n}f}"


B = lambda b, k: float(batches[b][k])
out = []
w = out.append
w(f"# E1 summary: {coh['cohort_id']}")
w("")
w(f"Generated by scripts/lib/e1_summary.py at {prov['commit']} ({prov['generated_utc']}). Do not edit; rerun "
  f"`scripts/post/g3-e1.cohort.sh {d}`.")
w(f"Run: {coh['nodes']} × {coh['instance_type']}, {coh['az']}, commit {coh['commit']}, spec {coh['spec']}, "
  f"{coh['start']} to {coh['stop']} (cohort.json).")
w("")
w("## Record notes")
w("")
w(f"- **Pre-fix engine (#44):** this run's engine ({coh['commit'][:7]}) predates the clean-room HitCounts (904c2a5), "
  "whose ResolveTree walks upstream's hit_counts order. By inference, only reads that hit an orphan taxonomy node "
  "(RODA v205 has 246) can differ; none of E1's 10 samples is among the 3 the U1 cross-check found "
  "(results/g3/campaign/prefix-engine.tsv).")
runlogs = sorted(glob.glob(os.path.join(d, "rank-*.run.log")))
streamed = {os.path.basename(p): sum(1 for l in open(p, errors="replace") if re.search(r"ak2-sample\s", l)) for p in runlogs}
total = sum(streamed.values())
if total == 0:
    w(f"- **E1's runs did not stream.** The rank run logs ({len(runlogs)} files, rank-*.run.log) contain 0 "
      "`ak2-sample` lines: the body's `> /dev/null` came before the `2> >(tee … | grep … | sed …)` "
      "process substitution, so the substitution's stdout was /dev/null. Only the per-invocation stderr "
      "pushes (`<member>/out/rank<r>/eng-<invocation>.stderr`) kept the data, and every table here is "
      "derived from them. A TTL kill mid-invocation would have lost that invocation's lines. Fixed in the "
      "spec after this run; `make rehearse` now asserts each rank streams `[c10] ak2-sample` lines.")
else:
    w(f"- Streaming: {total} `ak2-sample` lines across {len(runlogs)} rank run logs.")
w(f"- The run ended \"{coh['ended']}\" (cohort.json): rank 0's on-node consistency listing "
  "(list-object-versions) was denied, the instance role having no s3:ListBucketVersions. Every "
  "invocation had exited 0 on every rank before that step.")
w(f"- consistency.tsv, batches.tsv, samples.tsv, invocations.tsv and this file were computed after the run, "
  f"at {prov['commit']}, from {prov['consistency_source']} (sha256 {prov['outputs_tsv_sha256'][:16]}…) and "
  "tidy.tsv (provenance.tsv).")
nbad = sum(r["consistent"] != "yes" for r in cons)
vc = sorted({int(r["variants"]) for r in cons})
w(f"- Consistency: {len(cons)} sample files, {nbad} with more than one ETag; variants per file {vc} "
  "(consistency.tsv). E1 has no upstream arm and does not check Law 1.")
w(f"- Cost ${coh['cost_usd']:.2f} ({coh['cost_basis']}); orphans rc {coh['orphans_rc']}; multipart aborted "
  f"{coh['multipart_aborted']} (cohort.json).")
w("")
w("## Levers (each measured separately; no combined multiplier)")
w("")
w("| lever | comparison | A | B | ratio | source | note |")
w("|---|---|---|---|---|---|---|")
st, _ = c1_pair(tidy)
cli = [float(r["value"]) for r in tidy if r["rank"] == "0" and r["invocation"] == "c1-striped-cli"
       and r["kind"] == "phase" and r["metric"] == "classify"][0]
w(f"| L1 emitter, cohort 1 | SDK vs CLI, classify phase, rank 0 (s) | {f(st, 3)} | {f(cli, 3)} | {f(cli / st)}× | "
  "tidy.tsv c1-striped-sdk, c1-striped-cli | resolved: the same invocation's run-to-run spread is under 1% (input table below) |")
w(f"| L1 emitter, cohort 10 | SDK vs CLI, batch wall (s) | {f(B('0', 'wall_s'))} | {f(B('3', 'wall_s'))} | "
  f"{f(B('3', 'wall_s') / B('0', 'wall_s'))}× | batches.tsv 0, 3 | resolved |")
w(f"| L3 placement, cohort 10 | parallel vs striped, batch wall (s) | {f(B('0', 'wall_s'))} | {f(B('4', 'wall_s'))} | "
  f"{f(B('4', 'wall_s') / B('0', 'wall_s'))}× | batches.tsv 0, 4 | parallel's wall carries a {batches['0']['imbalance']}× "
  f"rank imbalance (max {batches['0']['rank_pairs_max']} vs mean {batches['0']['rank_pairs_mean']} pairs per rank, j mod N) |")
w(f"| L4 in flight | 2 vs 1, batch wall (s) | {f(B('1', 'wall_s'))} | {f(B('0', 'wall_s'))} | "
  f"{f(B('0', 'wall_s') / B('1', 'wall_s'), 3)}× | batches.tsv 0, 1 | rank 1 only (the bound rank), n=1, marginal |")
w(f"| threads | T8 vs T16 at in flight 2, batch wall (s) | {f(B('2', 'wall_s'))} | {f(B('1', 'wall_s'))} | — | "
  "batches.tsv 1, 2 | not a null: unresolvable (below) |")
loads = {}
for r in tidy:
    if r["rank"] == "0" and r["kind"] == "phase" and re.fullmatch(r"shard-load-\d+", r["metric"]):
        loads[r["invocation"]] = float(r["value"])
w(f"| L2 load once | c10: one load for {len(batches)} batches vs one load per invocation (s) | {f(loads['c10'], 1)} | "
  f"{', '.join(f(loads[k], 1) for k in sorted(loads) if k != 'c10')} | — | tidy.tsv shard-load-0, rank 0 | "
  f"a reload per batch would add about {len(batches) - 1} loads |")
w("")
bound = max({r["rank"] for r in samples if r["batch"] == "1"},
            key=lambda k: sum(int(r["pairs"]) for r in samples if r["batch"] == "1" and r["rank"] == k))
br = {b: [float(r["Mpairs_per_s"]) for r in samples if r["batch"] == b and r["rank"] == bound] for b in ("1", "2")}
w(f"**Threads.** The batch wall is set by rank {bound}, whose {len(br['1'])} in-flight samples ran at "
  f"{f(min(br['1']))}–{f(max(br['1']))} Mpairs/s each at T16 and {f(min(br['2']))}–{f(max(br['2']))} at T8 "
  "(samples.tsv), so the comparison could not resolve a thread effect: there is no threads null. Where a rank was "
  "exposed (single-sample ranks with at least 10M pairs):")
ss = {}
for r in samples:
    if r["batch"] in ("1", "2"):
        ss.setdefault((r["batch"], r["rank"]), []).append(r)
for b, t in (("1", "T16"), ("2", "T8")):
    rs = [float(v[0]["Mpairs_per_s"]) for (bb, _), v in ss.items() if bb == b and len(v) == 1 and int(v[0]["pairs"]) >= 10_000_000]
    w(f"- batch {b} ({t}): median {f(statistics.median(rs))} Mpairs/s, range {f(min(rs))}–{f(max(rs))}, n={len(rs)}")
w("")
w("## Input (decompress + parse): an added term")
w("")
w("Same-run pairs: one 10.5M-pair sample classified striped over 8 nodes (c1-striped-sdk, rank 0's classify "
  "phase) and on one home node (c1-parallel-sdk, its classify_s), in the same run:")
w("")
w("| cohort | striped, N=8 (s) | one node (s) | ratio |")
w("|---|---|---|---|")
pairs = []
for cj in sorted(glob.glob(os.path.join(os.path.dirname(d), "*", "cohort.json"))):
    c = json.load(open(cj))
    tp = os.path.join(os.path.dirname(cj), "tables", "tidy.tsv")
    if c.get("spec") != "runs/g3-e1.json" or not os.path.exists(tp):
        continue
    a, b = c1_pair(tsv(tp))
    if a and b:
        pairs.append((c["cohort_id"], a, b))
        w(f"| {c['cohort_id']} | {f(a, 3)} | {f(b, 3)} | {f(b / a, 3)} |")
w("")
r_in = [10532910 / a / 1e6 for _, a, _ in pairs]
w(f"Eight times the classify workers bought {f(100 * (statistics.mean(b / a for _, a, b in pairs) - 1), 1)}% on average: "
  f"the classify phase is held by a term that does not shrink with N. Each node reads the whole input as one "
  f"stream, at about {f(statistics.mean(r_in))} Mpairs/s here. It is named **input (decompress + parse)** because "
  "there is no plain-input control in E1 to separate decompression from parsing.")
w("")
w("Reported as an **addition** to the registered form, which stays as registered:")
w("")
w("    T(N) = t_boot + S/(N·B) + W/(N·c·r) + t_probe + t_gather + t_tail      (registered, #25)")
w("    t_input = W / r_input   (added; does not shrink with N; overlaps the W/(N·c·r) term,")
w("                             so the measured classify phase ≈ max(W/(N·c·r), t_input))")
w("")
w("t_input is reported separately in every table that uses T(N). In cost, a sample striped over N nodes pays "
  "about p·N·t_input.")
w("")
w("## Per-sample spread (batch 0: parallel, SDK, in flight 1, T16)")
w("")
b0 = [r for r in samples if r["batch"] == "0"]
rates = [float(r["Mpairs_per_s"]) for r in b0]
sizes = [int(r["pairs"]) for r in b0]
w(f"- {len(b0)} samples, {min(sizes) / 1e6:.1f}M–{max(sizes) / 1e6:.1f}M pairs; classify rate median "
  f"{f(statistics.median(rates), 3)} Mpairs/s, range {f(min(rates), 3)}–{f(max(rates), 3)} (samples.tsv). "
  "The smallest samples are overhead-bound.")
w("")
open(os.path.join(T, "summary.md"), "w").write("\n".join(out) + "\n")
print(f"e1_summary: {T}/summary.md ({len(pairs)} same-run input pairs)")
