#!/usr/bin/env bash
# make dryrun-userdata [GEN="EXP TYPE N COHORT; ..."] (docs/run.md, "DRY_RUN of every spec"):
# DRY_RUN=1 of every committed runs/*.json, plus specs generated by scripts/g3/mkspec.sh, through
# the driver a launch would use, and one record of the user-data size and the quota check:
#   results/rehearse/dryrun-userdata-<UTC>-<sha7>.tsv
# Launches nothing (DRY_RUN stops before the payload upload and the launch); its AWS calls are
# run.sh's and run-multi.sh's read-only pre-launch checks, the spawn --dry-run plan and the
# quota check's.
#
# Driver per spec: run-multi.sh when the spec pins resources.instance_type and
# placement.availability_zone (n = the body's WANT_N, else 1), run.sh otherwise.
# Generated specs: run.sh and run-multi.sh refuse an uncommitted spec, so each GEN entry is
# generated in a scratch git worktree of HEAD (under $TMPDIR), committed there on a detached HEAD
# (HEAD + the spec only; the record's scratch_commit column) and dry-run from it. The generated
# spec is copied beside the record (<record>.<spec basename>), and the worktree removed.
set +e
set -uo pipefail
ROOT=$(git rev-parse --show-toplevel) || exit 2
cd "$ROOT" || exit 2
echo "dryrun-userdata: shell flags $-" >&2
die() { echo "dryrun-userdata: $*" >&2; exit 2; }
GEN=${GEN:-}
[ -z "$(git status --porcelain -- scripts runs cmd internal upstream go.mod go.sum Makefile)" ] ||
  die "uncommitted changes; commit first (run.sh would refuse every spec)"
SHA7=$(git rev-parse --short=7 HEAD)
TS=$(date -u +%Y%m%dT%H%M%SZ)
mkdir -p results/rehearse
REC="results/rehearse/dryrun-userdata-$TS-$SHA7.tsv"
LOGD=$(mktemp -d "${TMPDIR:-/tmp}/ak2-dryrun.XXXXXX") || die "mktemp failed"
LIMIT=$((16384 - ${AK2_USERDATA_MARGIN:-1024}))
printf 'spec\tdriver\trc\tgzip_bytes\tlimit\theadroom\tquota\tscratch_commit\tnote\n' > "$REC"

# one REPO SPEC SCRATCH: dry-run SPEC from the checkout REPO, append a row.
one() {
  local repo=$1 spec=$2 scratch=$3 gate type az n driver log rc gz head quota note
  type=$(jq -r '.resources.instance_type // empty' "$repo/$spec")
  az=$(jq -r '.placement.availability_zone // empty' "$repo/$spec")
  log="$LOGD/$(basename "$spec" .json).log"
  # The gate the spec runs under (its task id and prefixes are in the user data): the name's
  # leading g<digit>[a-z], loadbench* g2, anything else g3.
  gate=$(basename "$spec" | grep -oE '^g[0-9][a-z]?')
  case $(basename "$spec") in loadbench*) gate=g2 ;; esac
  gate=${gate:-g3}
  if [ -n "$type" ] && [ -n "$az" ]; then
    n=$(jq -r '.command[2]' "$repo/$spec" | grep -oE '(^|[ ;])WANT_N=[0-9]+' | head -1 | grep -oE '[0-9]+$')
    n=${n:-1}; driver="run-multi n=$n"
    ( cd "$repo" && DRY_RUN=1 scripts/run-multi.sh "$gate" "$spec" "$n" ) > "$log" 2>&1; rc=$?
  else
    driver="run.sh"
    ( cd "$repo" && DRY_RUN=1 scripts/run.sh "$gate" "$spec" ) > "$log" 2>&1; rc=$?
  fi
  gz=$(grep -oE 'user data: [0-9]+ of 16384' "$log" | tail -1 | grep -oE '[0-9]+' | head -1)
  head=""; [ -n "$gz" ] && head=$((LIMIT - gz))
  # The cohort-wide check comes first in a run-multi log (rank 0's own, count 1, follows).
  quota=$(grep -E '^quota_check: (ok|REFUSED): ' "$log" | head -1 |
    sed -E 's/^quota_check: (ok|REFUSED): ([0-9]+) x ([^ ]+) = .* = ([0-9]+) of the .* quota (L-[0-9A-F]+) \(([0-9]+) vCPU\).*/\1 \2x\3 \4\/\6 \5/')
  note=""; [ "$rc" = 0 ] || note=$(grep -E 'make run|quota_check|accessions' "$log" | tail -1 | tr '\t' ' ' | cut -c1-200)
  [ "$rc" = 0 ] && [ -n "$gz" ] && [ "$gz" -gt "$LIMIT" ] && note="over the limit"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$spec" "$driver" "$rc" "${gz:--}" "$LIMIT" "${head:--}" "${quota:--}" "${scratch:--}" "$note" >> "$REC"
  echo "dryrun-userdata: $spec ($driver): rc $rc, user data ${gz:-?} B, quota ${quota:-?}" >&2
}

for s in runs/*.json; do one "$ROOT" "$s" ""; done

IFS=';' read -r -a GENS <<< "$GEN"
for g in "${GENS[@]}"; do
  read -r -a A <<< "$g"; [ "${#A[@]}" -ge 4 ] || { [ -z "${g// /}" ] && continue; die "GEN entry '$g' is not EXP TYPE N COHORT [KEY=VALUE...]"; }
  WT="$LOGD/wt-${A[0]}-${A[1]}-n${A[2]}"
  git worktree add -q --detach "$WT" HEAD || die "git worktree add failed"
  out=$( cd "$WT" && scripts/g3/mkspec.sh "${A[@]}" 2>&1 ); grc=$?
  SPEC="runs/g3-${A[0]}-${A[1]}-n${A[2]}.json"
  if [ $grc -ne 0 ] || [ ! -f "$WT/$SPEC" ]; then
    printf '%s\tmkspec\t%s\t-\t%s\t-\t-\t-\t%s\n' "$SPEC" "$grc" "$LIMIT" "$(echo "$out" | tail -1 | tr '\t' ' ')" >> "$REC"
  else
    git -C "$WT" add -A runs scripts/post && git -C "$WT" -c user.email=dryrun@aws-kraken2 -c user.name=dryrun-userdata \
      commit -qm "scratch: $SPEC (make dryrun-userdata; never pushed)" || die "scratch commit failed"
    SC=$(git -C "$WT" rev-parse --short=7 HEAD)
    cp "$WT/$SPEC" "$REC.$(basename "$SPEC")"
    one "$WT" "$SPEC" "$SC"
  fi
  git worktree remove --force "$WT" || echo "dryrun-userdata: WARNING: could not remove $WT" >&2
done
rm -rf "$LOGD"
BAD=$(awk -F'\t' 'NR > 1 && ($3 != 0 || ($6 != "-" && $6 + 0 < 0))' "$REC" | wc -l | tr -d ' ')
echo "dryrun-userdata: record $REC; $BAD spec(s) refused or over the limit" >&2
column -t -s $'\t' "$REC" >&2
[ "$BAD" = 0 ]
